In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df_train_10 = pd.read_excel('10_train.xlsx', header = None)
df_train_10["Conc"] = 10
df_train_50 = pd.read_excel('50_train.xlsx', header = None)
df_train_50["Conc"] = 50
df_train_75 = pd.read_excel('75_train.xlsx', header = None)
df_train_75["Conc"] = 75
df_test = pd.read_excel('100_test.xlsx', header = None)
df_train_300 = pd.read_excel('300_train.xlsx', header = None)
df_train_300["Conc"] = 300
df_train_500 = pd.read_excel('500_train.xlsx', header = None)
df_train_500["Conc"] = 500

In [ ]:
dfList = [df_train_10, df_train_75, df_train_300, df_train_500]
df_train = pd.concat(dfList)

In [ ]:
# df_train = pd.read_excel("train.xlsx") # For only one instance of each conc
df_train

0       1       2       3       4       5        6       7       8  \
0  249.80  252.90  256.80  261.00  265.90  271.60  278.500  286.70  296.10   
1  249.10  252.10  256.00  260.10  264.90  270.50  277.000  284.70  293.40   
2  246.80  249.90  253.50  257.70  262.40  267.80  274.200  281.60  290.00   
3  244.00  247.10  250.80  254.80  259.50  264.90  271.300  278.40  286.70   
0   35.35   35.84   36.49   37.13   37.98   38.95   40.050   41.44   43.09   
1   35.28   35.81   36.50   37.18   38.07   39.10   40.290   41.71   43.43   
2   35.05   35.59   36.29   36.99   37.89   38.94   40.160   41.61   43.36   
3   34.78   35.35   36.06   36.75   37.67   38.73   40.000   41.50   43.31   
0   15.89   14.78   13.97   13.16   13.02   12.91   13.360   14.04   15.16   
1   15.77   14.63   13.79   13.00   12.93   13.00   13.540   14.36   15.57   
2   15.67   14.49   13.65   12.89   12.87   13.06   13.630   14.57   15.85   
3   15.59   14.42   13.54   12.81   12.84   13.11   13.740   14.75   16.07   
0   16.05   14.24   12.91   11.58   10.89   10.20    9.921   10.46   11.31   
1   15.92   14.09   12.76   11.41   10.73   10.08    9.909   10.52   11.44   
2   15.89   14.06   12.70   11.37   10.70   10.05    9.919   10.56   11.43   
3   15.92   14.09   12.76   11.41   10.73   10.08    9.909   10.52   11.44   

        9  ...     93     94     95     96     97     98     99    100    101  \
0  307.40  ... -22770 -25970 -29390 -33090 -37190 -41370 -45950 -50730 -55850   
1  303.90  ... -25720 -29580 -33880 -38600 -43640 -49110 -55000 -61270 -68240   
2  300.00  ... -26420 -30460 -34860 -39720 -44930 -50540 -56400 -62810 -69900   
3  296.70  ... -27880 -32310 -37220 -42640 -48530 -54910 -61760 -69040 -76980   
0   45.03  ...  -9357 -10770 -12280 -13900 -15660 -17380 -19130 -21060 -23040   
1   45.49  ... -11970 -14000 -16280 -18820 -21610 -24650 -27940 -31240 -34700   
2   45.51  ... -13160 -15450 -18080 -21030 -24370 -28080 -32070 -36410 -41070   
3   45.48  ... -13710 -16120 -18880 -22010 -25560 -29530 -33910 -38730 -43760   
0   16.55  ...  -5555  -6258  -7024  -7803  -8606  -9393 -10170 -10890 -11560   
1   17.09  ...  -6972  -7966  -9052 -10210 -11420 -12670 -13940 -15190 -16300   
2   17.50  ...  -7304  -8355  -9517 -10760 -12070 -13420 -14780 -16110 -17290   
3   17.79  ...  -7514  -8623  -9818 -11120 -12490 -13910 -15330 -16680 -17920   
0   12.61  ...  -5231  -5888  -6593  -7321  -8075  -8817  -9546 -10250 -10820   
1   12.79  ...  -5697  -6436  -7230  -8068  -8920  -9780 -10590 -11350 -12040   
2   12.83  ...  -5847  -6613  -7420  -8253  -9089  -9896 -10630 -11290 -11800   
3   12.79  ...  -5697  -6436  -7230  -8068  -8920  -9780 -10590 -11350 -12040   

   Conc  
0    10  
1    10  
2    10  
3    10  
0    75  
1    75  
2    75  
3    75  
0   300  
1   300  
2   300  
3   300  
0   500  
1   500  
2   500  
3   500  

[16 rows x 103 columns]

In [ ]:
df_test = pd.read_excel("50_test.xlsx", header = None)
df_test

0      1      2      3      4      5      6      7      8      9    ...  \
0  55.89  56.82  57.91  59.05  60.42  62.00  63.80  65.94  68.33  71.26  ...   
1  55.64  56.59  57.63  58.77  60.16  61.75  63.58  65.66  68.14  71.12  ...   
2  55.27  56.13  57.22  58.32  59.66  61.18  62.95  65.08  67.64  70.56  ...   
3  54.70  55.54  56.58  57.63  58.92  60.40  62.11  64.16  66.56  69.50  ...   

     92     93     94     95     96     97     98     99     100    101  
0  -9830 -11380 -13090 -15030 -17110 -19320 -21790 -24470 -27150 -29820  
1 -11720 -13710 -15950 -18490 -21290 -24460 -27890 -31550 -35570 -39660  
2 -12510 -14020 -16710 -19810 -22920 -26470 -30330 -34520 -39090 -43890  
3 -12750 -14920 -17420 -20230 -23430 -26980 -30870 -35220 -39900 -44800  

[4 rows x 102 columns]

In [ ]:
# SVR-RBF
X = df_train.iloc[:, df_train.columns != "Conc"].values
y = df_train["Conc"].values
from sklearn.svm import SVR
regressor = SVR(gamma= 0.0001, kernel= 'rbf', C= 50)
regressor.fit(X, y)
regressor.predict(df_test)

array([187.5, 187.5, 187.5, 187.5])

In [ ]:
# SVR-POLY
from sklearn.svm import SVR
regressor = SVR(gamma= 0.001, kernel= 'poly', C= 5)
regressor.fit(X, y)
regressor.predict(df_test)

array([  61.32331278,   46.13925711, 1191.6432291 , -243.54433691])

In [ ]:
# XGBoost
# from xgboost import XGBRegressor
# regressor = XGBRegressor(objective="reg:squarederror")
# regressor.fit(X, y)
# regressor.predict(df_test)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=25)
regressor.fit(X, y)
regressor.predict(df_test)

array([75., 75., 75., 75.])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors = 4)
regressor.fit(X, y)
regressor.predict(df_test)

array([75., 75., 75., 75.])

In [ ]:
from sklearn.ensemble import AdaBoostRegressor
regressor = AdaBoostRegressor(random_state=0, n_estimators=100)
regressor.fit(X, y)
regressor.predict(df_test)

array([75., 75., 75., 75.])

In [ ]:
from sklearn.linear_model import BayesianRidge
regressor = BayesianRidge()
regressor.fit(X, y)
regressor.predict(df_test)

array([108.43852053,  93.49412634,  32.85914105, 104.884521  ])